// Auth Verify
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
// Login User
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
// Create User
export const CREATE_USER_LOADING = 'CREATE_USER_LOADING';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
// Get Active Campagins
export const GET_ACTIVE_CAMPAIGNS_LOADING = 'GET_ACTIVE_CAMPAIGN_LOADING';
export const GET_ACTIVE_CAMPAIGNS_SUCCESS = 'GET_ACTIVE_CAMPAIGNS_SUCCESS';
export const GET_ACTIVE_CAMPAIGNS_FAIL = 'GET_ACTIVE_CAMPAIGNS_FAIL' 
// Get Opportunity Campaigns
export const GET_OPPORTUNITY_CAMPAIGNS_LOADING = 'GET_OPPORTUNITY_CAMPAIGN_LOADING';
export const GET_OPPORTUNITY_CAMPAIGNS_SUCCESS = 'GET_OPPORTUNITY_CAMPAIGNS_SUCCESS';
export const GET_OPPORTUNITY_CAMPAIGNS_FAIL = 'GET_OPPORTUNITY_CAMPAIGNS_FAIL' 
// Get Inactive Campaigns
export const GET_NEGOTATION_CAMPAIGNS_LOADING = 'GET_NEGOTATION_CAMPAIGN_LOADING';
export const GET_NEGOTATION_CAMPAIGNS_SUCCESS = 'GET_NEGOTATION_CAMPAIGNS_SUCCESS';
export const GET_NEGOTATION_CAMPAIGNS_FAIL = 'GET_NEGOTATION_CAMPAIGNS_FAIL' 
// Get User
export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
// Log out
export const USER_LOGGED_OUT_SUCCESS = 'USER_LOGGED_OUT_SUCCESS'
